### ISSUE TITLE
Wrong property type size when enabling timeServer in config

### ISSUE THREAD

**Issue by Saubeer** [calimero-project/calimero-server#11]
Hi,
I got calimero server running without problems, but when I enable the timeServer in the config file
```
                <timeServer>
                        <datapoint stateBased="true" name="current date" dptID="10.001" priority="low">
                                <knxAddress type="group">1/1/36</knxAddress>
                                <expiration timeout="60" />
                        </datapoint>
                </timeServer>
```
I got this exception:
```
[main] ERROR calimero.server.knx-server - initialization of KNX server failed
tuwien.auto.calimero.device.ios.KnxPropertyException: property type size is 2, not 4, type conflict (write access with a wrong data type (datapoint length))
        at tuwien.auto.calimero.device.ios.InterfaceObject.setProperty(InterfaceObject.java:351)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer$IosAdapter.setProperty(InterfaceObjectServer.java:656)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer$IosAdapter.setProperty(InterfaceObjectServer.java:615)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer.setProperty(InterfaceObjectServer.java:422)
        at tuwien.auto.calimero.device.BaseKnxDevice.addGroupObject(BaseKnxDevice.java:487)
        at tuwien.auto.calimero.server.gateway.KnxServerGateway.setupTimeServer(KnxServerGateway.java:884)
        at tuwien.auto.calimero.server.gateway.KnxServerGateway.<init>(KnxServerGateway.java:704)
        at tuwien.auto.calimero.server.Launcher.run(Launcher.java:639)
        at tuwien.auto.calimero.server.Launcher.main(Launcher.java:613)

```
Same with `dptID="11.001"` or `dptID="19.001"`

**Comment by Saubeer** [comment]
Thank you for this quick fix. But now I get an other error:
```
[main] ERROR calimero.server.knx-server - initialization of KNX server failed
tuwien.auto.calimero.device.ios.KnxPropertyException: Group Object Table Object PID 23 property type size is 2, not 3, type conflict (write access with a wrong data type (datapoint length))
        at tuwien.auto.calimero.device.ios.InterfaceObject.setProperty(InterfaceObject.java:354)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer$IosAdapter.setProperty(InterfaceObjectServer.java:656)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer$IosAdapter.setProperty(InterfaceObjectServer.java:615)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer.setProperty(InterfaceObjectServer.java:422)
        at tuwien.auto.calimero.device.BaseKnxDevice.addGroupObject(BaseKnxDevice.java:505)
        at tuwien.auto.calimero.server.gateway.KnxServerGateway.setupTimeServer(KnxServerGateway.java:912)
        at tuwien.auto.calimero.server.gateway.KnxServerGateway.<init>(KnxServerGateway.java:754)
        at tuwien.auto.calimero.server.Launcher.run(Launcher.java:601)
        at tuwien.auto.calimero.server.Launcher.main(Launcher.java:575)
```

**Comment by bmalinowsky** [comment]
Can you remove the _knx-server-ios.xml_ file in the server dir, it probably has the old PDT stored from before the fix.

**Comment by Saubeer** [comment]
Perfect. Now it works. Thank you.
Just another question: Why I can't see the time and date telegrams in groupmonitor? Neither in ETS nor groupmonitor?

**Comment by bmalinowsky** [comment]
The server transmits the timestamp directly to the subnet (i.e., bus) and not to any client connections (because those don't really need it). You should see the timestamp msg if you have any other hardware (e.g., TP1 USB stick) connected to the KNX network. There it would show up, coming from the bus to any client. 

Do you have a use-case where you want the time server to also serve clients?

**Comment by calimero-project** [comment]
Timestamps are also forwarded to client connections now.

**Comment by Saubeer** [comment]
@bmalinowsky No I dont't have a use-case. I was just wondering why these messages are not visible. But thanks for adding the timestamp messages to the client connections. 👍
